image:
  - Visual Studio 2019

environment:
  matrix:
  - TOXENV: py38

build: false

install:
  # - py --list
  # - py -m pip install --upgrade pip
  - py -m pip install tox

test_script:
  - py -m tox
